### ISSUE TITLE
Please release a new tag

### ISSUE THREAD

**Issue by cryptiklemur** [nesQuick/ByteBuffer#1]
Looks like the master branch is pretty far ahead of v0.2. Would you mind releasing a new tag?

:D

**Comment by OleMchls** [comment]
Frankly I have no idea what happened since then. I would not feel confident to release / tag anything in this repo. What would just another tag change to just point to the master branch?

**Comment by cryptiklemur** [comment]
Because dev-master isn't a "stable release" as far as composer is concerned. Forces users to set `minimum-stability` to `dev` in their composer.json

**Comment by OleMchls** [comment]
there you go :)

https://github.com/nesQuick/ByteBuffer/tree/v0.3
